# Generated by Django 5.2.6 on 2025-09-26 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournament_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('budget_left', models.IntegerField(default=100000)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_badge', models.CharField(blank=True, max_length=40)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fantasyteam')),
            ],
        ),
    ]
