# Generated by Django 5.2.6 on 2025-09-26 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fantasyteam_fantasyroster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bo', models.IntegerField(default=3)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team1', to='core.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team2', to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=32)),
                ('map_index', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
            ],
            options={
                'ordering': ['match_id', 'map_index'],
                'unique_together': {('match', 'map_index')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMapStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('hs', models.IntegerField(default=0)),
                ('adr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('opening_kills', models.IntegerField(default=0)),
                ('opening_deaths', models.IntegerField(default=0)),
                ('flash_assists', models.IntegerField(default=0)),
                ('cl_1v2', models.IntegerField(default=0)),
                ('cl_1v3', models.IntegerField(default=0)),
                ('cl_1v4', models.IntegerField(default=0)),
                ('cl_1v5', models.IntegerField(default=0)),
                ('mk_3k', models.IntegerField(default=0)),
                ('mk_4k', models.IntegerField(default=0)),
                ('mk_5k', models.IntegerField(default=0)),
                ('utility_dmg', models.IntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.map')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['map'], name='core_player_map_id_fba883_idx'), models.Index(fields=['player'], name='core_player_player__d60b2b_idx')],
                'unique_together': {('map', 'player')},
            },
        ),
    ]
