# Generated by Django 5.2.6 on 2025-09-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_match_map_playermapstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='match',
            name='round_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='series_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('group', 'Group stage'), ('playoff', 'Playoff'), ('swiss', 'Swiss'), ('qual', 'Qualifier')], default='group', max_length=16),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'stage'], name='core_match_tournam_7be566_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['team1', 'team2', 'tournament'], name='core_match_team1_i_6488e1_idx'),
        ),
    ]
