# Generated by Django 5.2.6 on 2025-09-29 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_match_group_name_match_round_name_match_series_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='played_rounds',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='map',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
        migrations.AlterField(
            model_name='fantasyroster',
            name='fantasy_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_items', to='core.fantasyteam'),
        ),
        migrations.CreateModel(
            name='FantasyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('breakdown', models.JSONField(default=dict)),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_items', to='core.fantasyteam')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.map')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['fantasy_team', 'map'], name='core_fantas_fantasy_f3c589_idx'), models.Index(fields=['map'], name='core_fantas_map_id_15eb76_idx')],
                'unique_together': {('fantasy_team', 'map', 'player')},
            },
        ),
    ]
