# Generated by Django 5.2.6 on 2025-10-08 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_map_played_rounds_map_winner_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='world_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('source', models.CharField(choices=[('AUTO', 'Auto-calculated'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('calc_meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
            options={
                'indexes': [models.Index(fields=['tournament'], name='core_player_tournam_1e4a66_idx'), models.Index(fields=['player'], name='core_player_player__dfea3b_idx')],
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
