# Generated by Django 4.2.25 on 2025-10-25 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_team_world_rank_playerprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tournament participant',
                'verbose_name_plural': 'Tournament participants',
            },
        ),
        migrations.AlterModelOptions(
            name='map',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='fantasypoints',
            name='core_fantas_fantasy_f3c589_idx',
        ),
        migrations.RemoveIndex(
            model_name='fantasypoints',
            name='core_fantas_map_id_15eb76_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_tournam_7be566_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_team1_i_6488e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermapstats',
            name='core_player_map_id_fba883_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermapstats',
            name='core_player_player__d60b2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerprice',
            name='core_player_tournam_1e4a66_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerprice',
            name='core_player_player__dfea3b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='fantasypoints',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playermapstats',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playerprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='match',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='series_code',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_custom',
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fantasypoints',
            name='fantasy_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fantasyteam'),
        ),
        migrations.AlterField(
            model_name='fantasypoints',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fantasyroster',
            name='fantasy_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fantasyteam'),
        ),
        migrations.AlterField(
            model_name='fantasyroster',
            name='role_badge',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='budget_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='league',
            name='budget',
            field=models.PositiveIntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='league',
            name='lock_policy',
            field=models.CharField(default='soft', max_length=16),
        ),
        migrations.AlterField(
            model_name='league',
            name='max_badges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='league',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='core.tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='map_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='map',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='core.match'),
        ),
        migrations.AlterField(
            model_name='map',
            name='played_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tournament'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.team'),
        ),
        migrations.AlterField(
            model_name='playermapstats',
            name='adr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playermapstats',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='core.map'),
        ),
        migrations.AlterField(
            model_name='playermapstats',
            name='rating2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playermapstats',
            name='utility_dmg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprice',
            name='calc_meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='playerprice',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprice',
            name='source',
            field=models.CharField(default='calc', max_length=64),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fantasyteam',
            unique_together={('user', 'league')},
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.team'),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.tournament'),
        ),
        migrations.RemoveField(
            model_name='map',
            name='winner_team',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'team')},
        ),
    ]
