# Generated by Django 4.2.25 on 2025-11-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tournamentteam_alter_map_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprice',
            name='source',
            field=models.CharField(default='AUTO', max_length=16),
        ),
        migrations.CreateModel(
            name='PlayerHLTVStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating2', models.FloatField(default=0.0)),
                ('kills_per_round', models.FloatField(default=0.0)),
                ('adr', models.FloatField(default=0.0)),
                ('opening_kills_per_round', models.FloatField(default=0.0)),
                ('opening_deaths_per_round', models.FloatField(default=0.0)),
                ('win_after_opening', models.FloatField(default=0.0)),
                ('multikill_rounds_pct', models.FloatField(default=0.0)),
                ('clutch_points_per_round', models.FloatField(default=0.0)),
                ('sniper_kills_per_round', models.FloatField(default=0.0)),
                ('utility_damage_per_round', models.FloatField(default=0.0)),
                ('flash_assists_per_round', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hltv_stats', to='core.player')),
            ],
        ),
    ]
