# Generated by Django 4.2.25 on 2025-12-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_playerprice_source_playerhltvstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='roster_locked',
            field=models.BooleanField(default=False),
        ),
    ]
