# Generated by Django 4.2.25 on 2025-12-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fantasyteam_locked_at_fantasyteam_roster_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='team1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='team2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_wins', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='core.team'),
        ),
    ]
