# Generated by Django 4.2.25 on 2025-12-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_map_team1_score_map_team2_score_map_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='region_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='region_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
